config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount StripeEvent::Engine, at: '/stripe-webhooks'

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'

  resources :dolls, only: [:index, :show] do
    resources :reviews
  end
  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages
end

app/models/doll.rb
class Doll < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
  validates :price, presence: true
  monetize :price_cents
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :doll

  monetize :amount_cents
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :doll
  belongs_to :user

  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]
  has_many :dolls, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_one_attached :avatar

  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice("provider", "uid")
    user_params.merge! auth.info.slice("email", "first_name", "last_name")
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end

  def photo_url
    if avatar.attached?
      avatar.service_url
    else
      facebook_picture_url
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def show
    @chatroom = Chatroom.find(params[:id])
    @message = Message.new
    @chatrooms = Chatroom.all
  end
end

app/controllers/dolls_controller.rb
class DollsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @dolls = Doll.all
  end

  def show
    @doll = Doll.find(params[:id])
    @review = Review.new
    @reviews = Review.where(doll_id: @doll)
  end

  def new
    @new_doll = Doll.new
  end

  def create
    @new_doll = Doll.new(doll_params)
    @new_doll.user = current_user
    if @new_doll.save
      redirect_to doll_path(@new_doll)
    else
      render :new
    end
  end

  def edit
    @edit_doll = Doll.find(params[:id])
  end

  def update
    @update_doll = Doll.find(params[:id])
    @update_doll.update(doll_params)

    redirect_to doll_path(@update_doll)
  end

  private

  def doll_params
    params.require(:doll).permit(:name, :price, :description, :photo, :adopted)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @chatroom = Chatroom.find(params[:chatroom_id])
    @message = Message.new(message_params)
    @message.chatroom = @chatroom
    @message.user = current_user
    if @message.save
      ChatroomChannel.broadcast_to(
        @chatroom,
        render_to_string(partial: "message", locals: { message: @message })
      )
      redirect_to chatroom_path(@chatroom, anchor: "message-#{@message.id}")
    else
      render "chatrooms/show"
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    doll = Doll.find(params[:doll_id])
    order = Order.create!(doll: doll, doll_sku: doll.sku, amount: doll.price, state: 'pending', user: current_user)

    session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [{
        name: doll.sku,
        images: [doll.photo],
        amount: doll.price_cents,
        currency: 'eur',
        quantity: 1
      }],
      success_url: order_url(order),
      cancel_url: order_url(order)
    )

    order.update(checkout_session_id: session.id)
    redirect_to new_order_payment_path(order)
  end

  def show
    @order = current_user.orders.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home; end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
    @order = current_user.orders.where(state: 'pending').find(params[:order_id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_doll

  def create
    @review = Review.new(review_params)
    @review.doll = @doll
    @review.user = current_user
    respond_to do |format|
      if @review.save
        format.js { }
      end
    end
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end

  def set_doll
    @doll = Doll.find(params[:doll_id])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/chatrooms/show.html.erb
<div class="container">
  <div class="chatroom-box">
    <h1>#<%= @chatroom.name %></h1>
    <div id="messages" data-chatroom-id="<%= @chatroom.id %>">
      <% @chatroom.messages.each do |message| %>
        <%= render 'messages/message', message: message %>
      <% end %>
    </div>

    <%= simple_form_for [ @chatroom, @message ], remote: true do |f| %>
      <div class="d-flex flex-g">
        <div class="text-m">
          <%= f.input :content, label: false, placeholder: "Message ##{@chatroom.name}", input_html: { class: "form-inputs chat-m" } %>
        </div>
        <div class="enter-btn">
          <%= f.button :submit, "Send" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/dolls/index.html.erb
<div class="container">
  <div class="cards-grid">
        <% @dolls.each do |doll| %>
      <%= link_to doll_path(doll.id) do %>
        <div class="doll-card">
          <div class="doll-picture">
            <%= cl_image_tag doll.photo.key %>
          </div>
          <div class="doll-name-desc text-center mt-4 pb-4">
            <%= doll.name %>
          </div>

        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/dolls/show.html.erb
<div class="container">
  <div class="doll-card">
    <%= cl_image_tag @doll.photo.key, class:'banner-show'  %>
    <div class="doll-show-inf m-4 pb-4">
      <% if !@doll.adopted? %>
        <%= form_tag orders_path do %>
          <%= hidden_field_tag 'doll_id', @doll.id %>
          <%= submit_tag 'Adopt me!', class: 'btn messag-btn adoption-btn' %>
        <% end %>
      <% else %>
        <p class="adoption-btn messag-btn">I'm alreay adopted!</p>
      <% end %>
      <h4><%= @doll.name %></h4>
      <p><%= @doll.description %></p>
      <% if !@doll.adopted? %>
        <p>Amount: <%= humanized_money_with_symbol(@doll.price) %></p>
      <% end %>
    </div>

  </div>


  <div class="review-wall mb-4 mt-5">

    <div class="review-box">
      <% if !@doll.reviews.blank? %>
        <% @reviews.last(5).each do |review| %>
          <div class="review-card d-flex">
            <div class="small-avatar" style="background-image: url(<%= review.user.photo_url %>)"></div>
            <div class="review-info">
              <p><%= review.content %></p>
              <p class="date-string"><%= review.created_at.strftime("%-d %b %Y, %H:%M") %></p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <h4>Leave a message! 🐱</h4>
    <% if user_signed_in? %>
      <%= simple_form_for([ @doll, @review ], remote: true) do |f| %>
        <div class="d-flex flex-g">
          <div class="text-m">
            <%= f.input :content, as: :text, placeholder: 'Type a message', label: false, input_html: { class: "review-cont-input"} %>
          </div>
          <div class="secondarybtn-category-ex ml-2">
            <%= f.button :submit, 'Send', class: "category-color-button messag-btn" %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p>You need to login before leaving a message. 🍑</p>
    <% end %>

  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,700;1,800&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,400;1,700&display=swap" rel="stylesheet">
    <link rel="shortcut icon" href="https://res.cloudinary.com/drd5lqxx9/image/upload/v1608381264/favicon_h9eesn.ico"/>
  </head>

  <body>
    <div class="container">
      <%= render 'shared/navbar' %>
      <%= render 'shared/flashes' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="review-card d-flex">
  <div class="small-avatar" style="background-image: url(<%= message.user.photo_url %>)"></div>
  <div class="review-info">
    <p><%= message.user.first_name %>: <%= message.content %></p>
    <p class="date-string"><%= message.created_at.strftime("%-d %b %Y, %H:%M") %></p>
  </div>
</div>

app/views/orders/show.html.erb
<div class="container">
  <div class="row py-4">
    <div class="col-md-3"><%= image_tag @order.doll.photo_url, width: '100%' %></div>
    <div class="col">
      <h1>Order #<%= @order.id %> <small><span class="badge badge-primary"><%= @order.state %></span></small></h1>
      <ul class="list-unstyled">
        <li><strong>ISSUED ON</strong> <%= @order.created_at.to_date %></li>
        <li><strong>DOLL</strong> <%= @order.doll.name %> [<%= @order.doll_sku %>]</li>
        <li><strong>TOTAL</strong> <%= humanized_money_with_symbol @order.amount %></li>
        </li>
      </ul>
      <p>Estimated delivery in <strong>2 business days</strong></p>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container">
  <%= link_to dolls_path do %>
    <div class="banner-home d-flex home-card">
      <div class="home-btns">
        <div class="browse-dolls mt-2 ml-2">
          <p>Meet my friends</p>
        </div>
      </div>
    </div>
  <% end %>
  <div class="forum-coco home-card">
    <h4 class="mt-3">The Coco forum</h4>
    <p>Shall we get together? Join the community and make new friends!! You can choose one of our channels to start chatting. 💃</p> <br>
      <div class="forum-c colored-li">
        <%= link_to "#General", "/chatrooms/1" %>
      </div>
      <div class="forum-c">
        <%= link_to "#Blythe Customization", "/chatrooms/4" %>
      </div>
      <div class="forum-c colored-li">
        <%= link_to "#Requests", "/chatrooms/5" %>
      </div>
      <div class="forum-c">
        <%= link_to "#Fashion", "chatrooms/2" %>
      </div>
      <div class="forum-c colored-li">
        <%= link_to "#Off-topic", "/chatrooms/3" %>
      </div>
  </div>

  <div class="follow-ig home-card">
    <h4> <a href="https://www.instagram.com/la_cocco_violette/" target="_blank">Follow me on Instagram</a></h4>
  </div>

</div>

app/views/payments/new.html.erb
<div class="container">
  <div class="container">
    <div class="row py-4 checkout-card">
      <div class="col-md-3"><%= image_tag @order.doll.photo, width: '100%', class: 'checkout-photo' %></div>
      <div class="col mt-3">
        <h1>Checkout summary</h1>
        <p>Adoption of <strong><%= @order.doll.name %></strong> for <strong><%= humanized_money_with_symbol @order.amount %></strong></p>
        <button id="pay" class="btn messag-btn">Proceed</button>
        <script src="https://js.stripe.com/v3/"></script>
        <script>
          const paymentButton = document.getElementById('pay');
          paymentButton.addEventListener('click', () => {
            const stripe = Stripe('<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>');
            stripe.redirectToCheckout({
              sessionId: '<%= @order.checkout_session_id %>'
            });
          });
        </script>
      </div>
    </div>
  </div>
</div>

app/views/reviews/_review.html.erb
<div class="review-card d-flex">
  <div class="small-avatar" style="background-image: url(<%= @review.user.photo_url %>)"></div>
  <div class="review-info">
    <p><%= @review.content %></p>
    <p class="date-string"><%= @review.created_at.strftime("%-d %b %Y, %H:%M") %></p>
  </div>
</div>

app/views/reviews/create.js.erb
console.log("<%= escape_javascript (render partial: 'review', review: @review) %>")

const reviewBox = document.querySelector(".review-box");
const reviewInput = document.querySelector(".review-cont-input")

reviewBox.insertAdjacentHTML("beforeend", "<%= escape_javascript (render partial: 'review', review: @review) %>");
reviewInput.value = "";

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-coco">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://res.cloudinary.com/drd5lqxx9/image/upload/v1607129806/d570253c-49bb-44cb-95fb-374c3710562b_200x200_iryo2v.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </li>
        <li class="nav-item dropdown">
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>

</div>